### ISSUE TITLE
how to handle user-provided data before drawing

### ISSUE THREAD

**Issue by Xeverous** [heroseh/vui#1]
First of all, I would like to thank for this talk: https://www.youtube.com/watch?v=wsJ8Y1HO250 which I found on Dear ImGui's wiki. I found it to be a very valueable resource in how such library can be implemented.

I have recently started experimenting with making my own implementation and a thing that wasn't explained in the linked video is how to manage user-provided data that is needed for rendering.

Some background information before actual question: I have attempted to use Dear ImGui in one of my projects, however I encountered multiple issues that could not be solved or worked around satisfactory.

One of these issues is layout. Dear ImGui has basically no support for any other layout than top-to-bottom. The library has a concept of virtual cursor and every time you call any widget function (eg button, checkbox, label etc) it renders this widget in the point of the cursor and moves the cursor down. Dear ImGui has a column API but:

- Subcolumns within columns are impossible without borderless-window-inside-window cheats because columns (and a lot of other layout-affecting state) is implemented as singletons. ~95% of library's API are global functions that affect window-specific or global singleton. Some things can be nested by making more borderless windows and proper positioning but I have no idea how large overhead it creates.
- Columns API requires to provide column width on begin call. This is due to virtual cursor thing - columns have no layout mechanism, they are just big horizontally-fixed-size rectangles. Column API feels just like a wrapper around setting virtual cursor position. This puts width calculation on the library user, which IMO is a failure within IMGUI paradigm.

In the linked talk, I can see that in VUI the rendering does not happen immediately and there is no concept of virtual cursor, instead, in order:

1. library user makes a call to begin frame
2. library user makes calls to widgets
3. library user makes a call to end frame
4. library calculates the layout (potentially with multiple tree passes)
5. library renders the frame

**Now, my question is**: suppose that on the step 3 library user does something like `ui_label(some_temp_string)` and the string is destroyed immediately after the `ui_label` call. Dear ImGui does not need to deal with this lifetime problem because it layouts and renders everything immediately. How to handle this lifetime problem before step 5? How is it done in VUI?

I have looked at the source code and it seems that user-provided data is copied to a library-managed buffer:

https://github.com/heroseh/vui/blob/ced4e605cde3cfe18478c60282285cd7762d2fcf/vui.c#L2706-L2712

**I would like an explanation of this lifetime-problem solution.** Any GUI library will likely have a lot of functions that take user data (string, image, etc) so I'm interested of details how VUI handles/stores arbitrary amount of user-data of arbitrary type and then how it knows how to use this data in the rendering.

**Comment by heroseh** [comment]
hey there, wow i didn't realise i was in the Dear ImGUI wiki. cool stuff. I am glad you liked the video. yeah unfortunately the subject is very broad and it's hard to talk about everything :)

So as the nature of the IMGUI is dynamic and the state updated every frame. so the default lifetime of the data passed in is until the start of the next frame where you reset everything. There text example is a perfect case for this. we have an append only buffer that get reset at the start of a frame. When the user builds the UI we append this text to the buffer so the user's text doesn't have to worry about lifetime at all.

images (like text) are seen as primitive controls so we have places to store the auxiliary data (image_id is in VuiCtrl.image_id, text as  a append only text buffer which is pointed to by VuiCtrl.text_start_idx or something).

if you have data that must persist between frames and the type is truely unknown. try to either boil these types down to a single type like VuiCtrl and VuiCtrlStyle (this means we can reason able a size and align). or create something like the vui_image_add functions that make the persistent state that you pass a identifier/handle around for the controls to access.

but again, remember to stick to lifetime by default is the frame. this way the data can be dynamic with the nature of the IMGUI. but if that does not matter like the case of Images. then go with the identifier approach.

I hope that helps :)

**Comment by Xeverous** [comment]
Yes, this explains the approach, I thought it could be something more complex but apparently you just append the data to a buffer that is reset each frame. Other state is either made persistent and user refers to it through IDs or it is inside the widget control structure - am I right?

**Comment by Xeverous** [comment]
Another question: I saw that the `VuiCtrl` is forming a tree and the tree is optimized by a pool allocator. Do you think there is any data structure that could serve the purpose better? I'm thinking of a flat set which initially does 1 allocation and then allows adding elements 1 by 1 and then clear them all at once - if I inferred the idea right the layout tree is build 1 by 1 and then cleared each frame so there is a possibility for optimized data structure that supports only adding 1 element and clearing all elements.
